api = "0.4"

[buildpack]
homepage = "https://github.com/laraboot-io/shared"
id = "laraboot-io/shared"
name = "Laraboot Shared Lib"
version = "{{ .Version }}"

[metadata]
include_files = ["bin/build", "bin/detect", "buildpack.toml"]
pre_package = "./scripts/build.sh"
[metadata.default-versions]
composer = "*"

[[stacks]]
id = "org.cloudfoundry.stacks.cflinuxfs3"

[[stacks]]
id = "io.buildpacks.stacks.bionic"